version: "3.5"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
    networks:
      - dbnet
    ports: 
    - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ssl-2000
  console:
    build: .
    depends_on:
      - mssql
    networks:
      - dbnet
    links:
      - mssql:mssql

networks:
  dbnet:
    driver: bridge

    
      
        

           